### PR TITLE
[TOREVIEW] Besseau_Ogi

### PR DESCRIPTION
**Pull request by LeonardBesseau**

### CODE REVIEW

**Comment by LeonardBesseau** [comment]
Still waiting on an answer about the DFS. Should it treat the files first as in the documentation or explore sub-directories first as in the test of the application ?

**Comment by LeonardBesseau** [comment]
> Still waiting on an answer about the DFS. Should it treat the files first as in the documentation or explore sub-directories first as in the test of the application ?

DFS is all good. Test correspond to what is expected. Documentation still has to be changed

**Comment by LeonardBesseau** [comment]
Documentation for DFS changed

**Comment by LeonardBesseau** [comment]
For information DFS test was modified to also consider files instead of only folders. The expected behaviour is that the explorer should first visit the folders recursively and then visit the files

**Comment by NicolasOgi** [comment]
Test was failing on Windows due to ApplicationTest waiting for \n as line separator and System.lineSeparator() returned \r\n.

**Pull request closed without merging**
